apiVersion: v1
kind: Service
metadata:
  name: mysite
spec:
  selector:
    app: mysite
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: mysite
        image: digantagu/mysite:26
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
